### ISSUE TITLE
API is not available

### ISSUE THREAD

**Issue by eivantsov** [code-ready/osp4#56]
I have downloaded tar, created and started cluster, exported kubeconfig, however oc cannot connect to server:

```
eugene@ivantsoft ~/Downloads/crc_libvirt_0.16.1 $ oc get pods
The connection to the server api.test1.tt.testing:6443 was refused - did you specify the right host or port?
```

Interestingly, a router is available:

![image](https://user-images.githubusercontent.com/5337267/55875354-93d95e00-5b9d-11e9-89ea-59994d0abcf3.png)

The VM is using resources:

![image](https://user-images.githubusercontent.com/5337267/55875372-9dfb5c80-5b9d-11e9-9cb6-bee54afe04a9.png)

**Comment by praveenkumar** [comment]
@eivantsov `6443` is where apiserver runs so it might be the case that it is crashed or just reconciling, have you waited for some time after the crc start?

**Comment by praveenkumar** [comment]
@eivantsov I am closing this issue since you had dnsmasq file in the `/etc/NetworkManager/dnsmasq.d/openshift.conf` which was not updated correctly, on our side we need to take an action item so it will update in future.
